[package]
name = "runes_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorize = "0.1.0"
dyn-clone = "1.0.11"
minimax = "0.5.1"
